# Generated by Django 4.0.4 on 2022-05-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=120)),
                ('model', models.PositiveIntegerField(null=True)),
                ('killometer_run', models.PositiveIntegerField(null=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
