# Generated by Django 4.0.4 on 2022-06-06 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usedbikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikeprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikename', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('model', models.PositiveIntegerField(null=True)),
                ('logo', models.ImageField(null=True, upload_to='bikeprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
