# Generated by Django 4.0.4 on 2022-06-18 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usedbikes', '0002_bikes_bike_photo_bikes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='bike_photo',
            field=models.ImageField(null=True, upload_to='bike_photo'),
        ),
        migrations.CreateModel(
            name='BikeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sending', 'sending'), ('viewed', 'viewed'), ('reject', 'reject'), ('cancelled', 'cancelled')], default='sending', max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usedbikes.bikes')),
            ],
        ),
    ]
