# Generated by Django 4.0.4 on 2022-06-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedbikes', '0003_alter_bikes_bike_photo_bikeapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('viewed', 'viewed'), ('reject', 'reject'), ('cancelled', 'cancelled')], default='sending', max_length=120),
        ),
    ]
